services:
  backend-loto:
    build:
      context: ./backend
    container_name: loto-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped

  backend-chat:
    build:
      context: ./chat
    container_name: chat-backend
    ports:
      - "8081:8081"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: loto-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-loto
      - backend-chat
    restart: unless-stopped
